//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.8.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Playground;

namespace Playground_Model.Screens.DesktopApp
{
    [Screen]
    public partial class RecentSign_InActivity : Progile.TRIO.BaseModel.BaseScreen
    {
        public RecentSign_InActivity(PlaygroundApp app) : base(app, @"Recent Sign-In Activity", Images.DesktopApp.RecentSign_InActivity.Screen_Loaded)
        {
            App = app;
            RecentSign_InActivityTable = new RecentSign_InActivityTable(app) { ParentElement = this };
            PDFIconButton = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "PDF Icon Button", activeImageReference: Images.DesktopApp.RecentSign_InActivity.PDFIconButton.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private PlaygroundApp App { get; set; }
        public RecentSign_InActivityTable RecentSign_InActivityTable { get; private set; }

        public Progile.TRIO.BaseModel.Button PDFIconButton { get; private set; }

        partial void ConfigureElementProperties();
    }
}