//------------------------------------------------------------------------------
//
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.8.0.0
// Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated.
// </auto-generated>
//
//------------------------------------------------------------------------------

using System;
using Progile.TRIO.BaseModel;
using Progile.ATE.TestFramework;
using static TestImages.Playground;

namespace Playground_Model.Screens.DesktopApp
{
	[Table]
	public partial class RecentSign_InActivityTable : TableBase<Column, Row>
	{
		public RecentSign_InActivityTable(PlaygroundApp app) : base(app, "Recent Sign-In Activity Table", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.UserName, true)
		{
			App = app;
			UserName = new Column(app, "User Name", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.UserName, TableRect, true) {ParentElement = this};
			JobTitle = new Column(app, "Job Title", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.JobTitle, TableRect, true) {ParentElement = this};
			CompanyName = new Column(app, "Company Name", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.CompanyName, TableRect, true) {ParentElement = this};
			Country = new Column(app, "Country", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.Country, TableRect, true) {ParentElement = this};
			LastInvoice = new Column(app, "Last Invoice", Images.DesktopApp.RecentSign_InActivity.RecentSign_InActivityTable.LastInvoice, TableRect, true) {ParentElement = this};

			ConfigureElementProperties();
		}

		private PlaygroundApp App;

		[ModelCapability]
		public Column UserName { get; private set; }

		[ModelCapability]
		public Column JobTitle { get; private set; }

		[ModelCapability]
		public Column CompanyName { get; private set; }

		[ModelCapability]
		public Column Country { get; private set; }

		[ModelCapability]
		public Column LastInvoice { get; private set; }

		partial void ConfigureElementProperties();
	}
}
