//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.8.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.Playground;

namespace Playground_Model.Screens.WebApp
{
    [Screen]
    public partial class LoginConfirmation : Progile.TRIO.BaseModel.BaseScreen
    {
        public LoginConfirmation(PlaygroundApp app) : base(app, @"Login Confirmation", Images.WebApp.LoginConfirmation.Screen_Loaded)
        {
            App = app;
            ConfirmationCode = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Confirmation Code", imageReference: Images.WebApp.LoginConfirmation.ConfirmationCode, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            Language = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "Language", imageReference: Images.WebApp.LoginConfirmation.Language.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            MobileLink = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "Mobile Link", activeImageReference: Images.WebApp.LoginConfirmation.MobileLink.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            CONFIRM = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "CONFIRM", activeImageReference: Images.WebApp.LoginConfirmation.CONFIRM.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            RememberLanguage = new Progile.TRIO.BaseModel.LabelWithCheckbox(appBasics: AppBasics, displayName: "Remember Language", checkboxPosition: RelativePosition.Left, imageReferenceForLabel: Images.WebApp.LoginConfirmation.RememberLanguage.LabelImage, checkedImageReference: Images.WebApp.LoginConfirmation.RememberLanguage.Checkbox._checked, uncheckedImageReference: Images.WebApp.LoginConfirmation.RememberLanguage.Checkbox._unchecked, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private PlaygroundApp App { get; set; }
        public Progile.TRIO.BaseModel.TextBox ConfirmationCode { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown Language { get; private set; }

        public Progile.TRIO.BaseModel.Button MobileLink { get; private set; }

        public Progile.TRIO.BaseModel.Button CONFIRM { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithCheckbox RememberLanguage { get; private set; }

        partial void ConfigureElementProperties();
    }
}