//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using NewSimulation_Model.Screens;

namespace NewSimulation_Model
{
    [SoftwareModel]
    public partial class NewSimulationApp : IAppBasics
    {
        partial void InitScreens()
        {
            InvoicePDF = new InvoicePDF(this);
            LoginConfirmation = new LoginConfirmation(this);
            LoginScreen = new LoginScreen(this);
            Mobile = new Mobile(this);
            RecentSign_InActivity = new RecentSign_InActivity(this);
        }


        public InvoicePDF InvoicePDF { get; set; }
        
        public LoginConfirmation LoginConfirmation { get; set; }
        
        public LoginScreen LoginScreen { get; set; }
        
        public Mobile Mobile { get; set; }
        
        public RecentSign_InActivity RecentSign_InActivity { get; set; }
        
    }
}