//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.NewSimulation;

namespace NewSimulation_Model.Screens
{
    [Screen]
    public partial class InvoicePDF : Progile.TRIO.BaseModel.BaseScreen
    {
        public InvoicePDF(NewSimulationApp app) : base(app, @"Invoice PDF", Images.InvoicePDF.Screen_Loaded)
        {
            App = app;
            Total = new Progile.TRIO.BaseModel.LabelWithValue(appBasics: AppBasics, displayName: "Total", valuePosition: RelativePosition.Right, imageReferenceForLabel: Images.InvoicePDF.Total, filters: ScreenSelect) { ParentElement = this };
            Rate_Price = new Progile.TRIO.BaseModel.LabelWithValue(appBasics: AppBasics, displayName: "Rate/Price", valuePosition: RelativePosition.Below, searchTextForLabel: "Rate/Price", filters: ScreenSelect) { ParentElement = this };
            Tax = new Progile.TRIO.BaseModel.LabelWithValue(appBasics: AppBasics, displayName: "Tax", valuePosition: RelativePosition.Below, imageReferenceForLabel: Images.InvoicePDF.Tax, filters: ScreenSelect) { ParentElement = this };
            Total.AnchorElement = Tax;

            ConfigureElementProperties();
        }


        private NewSimulationApp App { get; set; }
        public Progile.TRIO.BaseModel.LabelWithValue Total { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithValue Rate_Price { get; private set; }

        public Progile.TRIO.BaseModel.LabelWithValue Tax { get; private set; }

        partial void ConfigureElementProperties();
    }
}