//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.NewSimulation;

namespace NewSimulation_Model.Screens
{
    [Screen]
    public partial class LoginScreen : Progile.TRIO.BaseModel.BaseScreen
    {
        public LoginScreen(NewSimulationApp app) : base(app, @"Login Screen", Images.LoginScreen.Screen_Loaded)
        {
            App = app;
            EmailAddress = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Email Address", imageReference: Images.LoginScreen.EmailAddress, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            Password = new Progile.TRIO.BaseModel.PwTextBox(appBasics: AppBasics, displayName: "Password", imageReference: Images.LoginScreen.Password.TextBoxImage, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            LOGIN = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "LOGIN", activeImageReference: Images.LoginScreen.LOGIN.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private NewSimulationApp App { get; set; }
        public Progile.TRIO.BaseModel.TextBox EmailAddress { get; private set; }

        public Progile.TRIO.BaseModel.PwTextBox Password { get; private set; }

        public Progile.TRIO.BaseModel.Button LOGIN { get; private set; }

        partial void ConfigureElementProperties();
    }
}