//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.NewSimulation;

namespace NewSimulation_Model.Screens
{
    [Screen]
    public partial class LoginConfirmation : Progile.TRIO.BaseModel.BaseScreen
    {
        public LoginConfirmation(NewSimulationApp app) : base(app, @"Login Confirmation", Images.LoginConfirmation.Screen_Loaded)
        {
            App = app;
            ConfirmationCode = new Progile.TRIO.BaseModel.TextBox(appBasics: AppBasics, displayName: "Confirmation Code", imageReference: Images.LoginConfirmation.ConfirmationCode, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            Language = new Progile.TRIO.BaseModel.Dropdown(appBasics: AppBasics, displayName: "Language", imageReference: Images.LoginConfirmation.Language.DropdownTextBox, useVisualSense: true, filters: ScreenSelect) { ParentElement = this };
            MobileLink = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "Mobile Link", activeImageReference: Images.LoginConfirmation.MobileLink.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };
            CONFIRM = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "CONFIRM", activeImageReference: Images.LoginConfirmation.CONFIRM.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private NewSimulationApp App { get; set; }
        public Progile.TRIO.BaseModel.TextBox ConfirmationCode { get; private set; }

        public Progile.TRIO.BaseModel.Dropdown Language { get; private set; }

        public Progile.TRIO.BaseModel.Button MobileLink { get; private set; }

        public Progile.TRIO.BaseModel.Button CONFIRM { get; private set; }

        partial void ConfigureElementProperties();
    }
}