//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.6.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using static TestImages.NewSimulation;

namespace NewSimulation_Model.Screens
{
    [Screen]
    public partial class Mobile : Progile.TRIO.BaseModel.BaseScreen
    {
        public Mobile(NewSimulationApp app) : base(app, @"Mobile", Images.Mobile.Screen_Loaded)
        {
            App = app;
            ConfirmationCode = new Progile.TRIO.BaseModel.LabelWithValue(appBasics: AppBasics, displayName: "Confirmation Code", valuePosition: RelativePosition.Right, imageReferenceForLabel: Images.Mobile.ConfirmationCode, gridWidth: 250, filters: ScreenSelect) { ParentElement = this };
            WebapplicationLink = new Progile.TRIO.BaseModel.Button(appBasics: AppBasics, displayName: "Webapplication Link", activeImageReference: Images.Mobile.WebapplicationLink.active, useVisualSense: false, filters: ScreenSelect) { ParentElement = this };

            ConfigureElementProperties();
        }


        private NewSimulationApp App { get; set; }
        public Progile.TRIO.BaseModel.LabelWithValue ConfirmationCode { get; private set; }

        public Progile.TRIO.BaseModel.Button WebapplicationLink { get; private set; }

        partial void ConfigureElementProperties();
    }
}