//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the TestResults.io Designer.
// Designer Version: 5.8.0.0
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Progile.TRIO.BaseModel;
using Playground_Model.Screens;

namespace Playground_Model
{
    [SoftwareModel]
    public partial class PlaygroundApp : IAppBasics
    {
        partial void InitScreens()
        {
            LoginScreen = new LoginScreen(this);
        }


        public LoginScreen LoginScreen { get; set; }
        
    }
}